# Site settings
title: Angela Lin | Full Stack Developer
description: Welcome to Angela Lin's Portfolio
# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: "http://ang.world" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Angela Lin
user_description: Hi, I'm Angela, a full stack developer based in NYC. I love climbing/bouldering, exploring bookstores, and learning languages.
user_title: Full Stack Developer
email: angela.ts.lin@gmail.com
stack_username: 6555276
github_username:  tigclaw
linkedin_username:  angelatlin

# Google-analytics
google-analytics:
  id: "UA-75844268-1"

exclude: ['package.json', 'src' , 'node_modules']
